version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:current
    parallelism: 2
    steps:
      - checkout
      - run:
          name: install
          command: npm install --include=dev
      - run:
          name: run tests
          environment:
            JEST_JUNIT_ADD_FILE_ATTRIBUTE: "true"
          command: ls ./*.test.js | circleci tests split --split-by=timings --timings-type=filename | xargs npx jest --ci --reporters=default --reporters=jest-junit --
      - run:
          command: mkdir -p ~/junit && cp junit.xml ~/junit/
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
